service: logging-${opt:timestamp}

provider:
  name: google
  stackName: logging-${opt:timestamp}
  project: faastest
  credentials: /tmp/.gcloud/faasbenchmark.json
  stage: dev

plugins:
  - serverless-google-cloudfunctions
  
functions:
  log-node810-128mb:
    name: --log-node810-128mb-${opt:timestamp}
    description: log stress function 128mb
    runtime: nodejs8
    handler: test128
    memorySize: 128
    events:
      - http: path

  log-node810-256mb:
    name: --log-node810-256mb-${opt:timestamp}
    description: log stress function 256mb
    runtime: nodejs8
    handler: test256
    memorySize: 256
    events:
      - http: path

  log-node810-512mb:
    name: --log-node810-512mb-${opt:timestamp}
    description: log stress function 512mb
    runtime: nodejs8
    handler: test512
    memorySize: 512
    events:
      - http: path

  log-node810-1024mb:
    name: --log-node810-1024mb-${opt:timestamp}
    description: log stress function 1024mb
    runtime: nodejs8
    handler: test1024
    memorySize: 1024
    events:
      - http: path

  log-node810-2048mb:
    name: --log-node810-2048mb-${opt:timestamp}
    description: log stress function 2048mb
    runtime: nodejs8
    handler: test2048
    memorySize: 2048
    events:
      - http: path
